# what is a hash table?
# it is a data type in which the address or the index of the data element is generated by a hash function
# in python, a hash table is implemented by a dictionary
# searching and inserting is faster in a hash table
# elements are not ordered
# hashing function generates unique values

# declare a hash / dictionary
my_dict = {'toy': 'marble', 'date': 'holiday', 'location': 'Maryland', 'people': 'lake family'}

# access the dictionary using key
toy = my_dict['toy']
date = my_dict['date']
people = my_dict['people']
print('some key values: ', toy, date, people)

print('-----------------------')

# updating a dictionary
my_dict['toy'] = 'lego'
my_dict['date'] = 'Shanna birthday'
my_dict['location'] = 'home'
my_dict['people'] = 'Sega, Corinne, Liz, Shanna, Jeylan, Lani'

print('updated my_dict: ', my_dict)

print('-----------------------')

# add and remove elements from a hash table
copy_my_dict = my_dict.copy()
print('copy of my_dict: ', copy_my_dict)
copy_my_dict['year'] = 2021
copy_my_dict['irrelevant'] = 'eat and drink'
print('updated copy of my_dict: ', copy_my_dict)
copy_my_dict.clear()
print('cleared copy of my_dict: ', copy_my_dict)

